### PR TITLE
Create contributing.md

### PR DESCRIPTION
**Pull request by nayasinghania**
added contributing.md file + basic heading. Not sure what info to put inside as I am unaware of any specific coding styles or contribution rules that the BuildFormAI devs are following. Please let me know if I should add some generic contributing guidelines to this file.

### CODE REVIEW

**Comment by zeul22** [comment]
Please add generic contributing guidelines.

**Comment by nayasinghania** [comment]
I've added generic contributing guidelines. I didnt see a license that was in the project so I left a placeholder for anything referencing a license. If you know what license you want to use, I can add that information into the contributing guidelines. Please let me know if any other changes are needed. Thanks

**Comment by zeul22** [comment]
We are moving forward with MIT License, would you add that? Thanks.

**Comment by nayasinghania** [comment]
Ok great! I've added that in. Please let me know if any other changes are needed. Thanks

**Comment by zeul22** [comment]
Hi, this looks great! thanks for the contribution, there are other good first issues to solve if you are interested!

**Comment by nayasinghania** [comment]
Great, I'll take a look

**Pull request merged**
